project:
  type: website

website:
  title: "O novo mapa das capitanias heredit√°rias"
  navbar:
    left:
      - href: Presentation-EducaSER.qmd


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



